### ISSUE TITLE
"code = 'put_your_code_here'." là cái gì?

### ISSUE THREAD

**Issue by KhanhJobs** [zaloplatform/zalo-python-sdk#5]
> Lấy LoginUrl
> 
> login_url = zalo_3rd_app_client.get_login_url()
> Lấy AccessToken
> 
> code = 'put_your_code_here'
> access_token = zalo_3rd_app_client.get_access_token(code)

code có phải là đoạn code sau chữ code = của login_url trả về?

> http://example.com?uid=_________________________&code=______________________________________F2uZ8YO5Q5FcVoxZhytz3UEf6lrEtt87uG-

**Comment by zaloplatform** [comment]
Chào bạn,
Code ở đây chính là OAuthCode, chỉ có sử dụng OAuthCode bạn mới có thể lấy access token !
**Để trước khi sử dụng sdk, bạn vào link sau để tìm hiểu api của zalo nhé** https://developers.zalo.me/docs/api/social-api-4
Nếu có thắc mắc, bạn có thể vào page https://developers.zalo.me/community/ để được supporter hỗ trợ,
Best regards.

**Comment by yukatat** [comment]
vậy rút cục lấy cái OAuthCode đó lấy như thế nào vậy AD
