### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by tuananh1406** [zaloplatform/zalo-python-sdk#9]
Chào bạn, mình đang thử làm app zalo chat bằng python. Nhưng sau khi khởi tạo app thì có thông báo như sau:
  File "chat.py", line 2, in <module>
    from zalo.sdk.app import ZaloAppInfo, Zalo3rdAppClient
  File "./site-packages/zalo/sdk/app/__init__.py", line 2, in <module>
    from .Zalo3rdAppClient import Zalo3rdAppClient
  File "./site-packages/zalo/sdk/app/Zalo3rdAppClient.py", line 1, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by yukatat** [comment]
Tải module requests về mà làm:
pip install requests

**Comment by yukatat** [comment]
sau đó import requests. vào chương trình. thực ra còn cần cái thêm mấy cái module nữa. python báo thiếu cái nào thì cài cái đó là dc dùng pip cài cho nhanh. Close dùm nha
